title = "Amazonka"
theme = "theme"
baseURL = "https://amazonka.brendanhay.nz"
metaDataFormat = "yaml"
defaultContentLanguage = "en"
disablePathToLower = true
enableGitInfo = false

[Languages.en]
languageName = "English"
languageCode = "en-UK"
landingPageURL = "/"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
# See the config.toml file from this documentation site to have an example.
editURL = ""
# Author of the site, will be used in meta information
author = "Brendan Hay"
# Description of the site, will be used in meta information
description = ""
# Shows a checkmark for visited pages on the menu
showVisitedLinks = false
# Disable search function. It will hide search bar
disableSearch = false
# Javascript and CSS cache are automatically busted when new version of site is generated.
# Set this to true to disable this behavior (some proxies don't handle well this optimization)
disableAssetsBusting = true
# Set this to true to disable copy-to-clipboard button for inline code.
disableInlineCopyToClipBoard = false
# A title for shortcuts in menu is set by default. Set this to true to disable it.
disableShortcutsTitle = true
# If set to false, a Home button will appear below the search bar on the menu.
# It is redirecting to the landing page of the current language if specified. (Default is "/")
disableLandingPageButton = true
# When using mulitlingual website, disable the switch language button.
disableLanguageSwitchingButton = true
# Hide breadcrumbs in the header and only show the current page title
disableBreadcrumb = false
# If set to true, prevents Hugo from including the mermaid module if not needed (will reduce load times and traffic)
disableMermaid = true
# Hide Next and Previous page buttons normally displayed full height beside content
disableNextPrev = true
# Order sections in menu by "weight" or "title". Default to "weight"
ordersectionsby = "weight"
# Provide a list of custom css files to load relative from the `static/` folder in the site root.
custom_css = ["css/custom.css"]
# Change the title separator. Default to "::".
titleSeparator = "-"

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-angle-double-right'></i> Code"
url = "https://github.com/brendanhay/amazonka"
weight = 10

[[menu.shortcuts]]
name = "<i class='far fa-fw fa-chart-bar'></i> Contributors"
url = "https://github.com/brendanhay/amazonka/graphs/contributors"
weight = 20

[[menu.shortcuts]]
name = "<i class='far fa-fw fa-dot-circle'></i> Issues"
url = "https://github.com/brendanhay/amazonka/issues"
weight = 30

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-amazon'></i> AWS Documentation"
url = "https://docs.aws.amazon.com"
weight = 100